export const SET_STOCK = "SET_STOCK";
export const SET_FAVORITES_STOCKS_SYMBOL = "SET_FAVORITES_STOCKS_SYMBOL";
export const SET_FAVORITE_STOCK_LIST = "SET_FAVORITE_STOCK_LIST";
export const SET_LATEST_UPDATE_TIME = "SET_LATEST_UPDATE_TIME";
export const SET_ERROR = "SET_ERROR";
